### ISSUE TITLE
Compatibility with WP 5.4

### ISSUE THREAD

**Issue by sudar** [sudar/delete-pending-comments#1]
- [x] Check compatibility with WordPress 5.4

**Comment by esudalaimadan** [comment]
@sudar Even after deleting pending comments(comments are getting deleted), pending comments count is being shown in comments listing page.  I have used our `Bulk Delete Comments`, it is deleting correctly and pending comments count is displayed correctly.

**Comment by sudar** [comment]
@esudalaimadan 

As we discussed today in the call, find out how to recount comment count.

**Comment by esudalaimadan** [comment]
Created following tickets for errors or warnings in log:
https://github.com/sudar/delete-pending-comments/issues/3
https://github.com/sudar/delete-pending-comments/issues/4
https://github.com/sudar/delete-pending-comments/issues/5
https://github.com/sudar/delete-pending-comments/issues/6
